### ISSUE TITLE
Erlang/Mix broken

### ISSUE THREAD

**Issue by nivanson** [Microsoft/BashOnWindows#106]
Mix cannot run.

```
root@localhost:/mnt/c/Users/Nils/Desktop/src/test# mix help
** (ErlangError) erlang error: :terminated
    (stdlib) :io.put_chars(#PID<0.25.0>, :unicode, [[[], "mix app.start           # Starts all registered apps"], 10])
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/tasks/help.ex:51: Mix.Tasks.Help.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Erlang version: 18.3
Windows version: 14316.rs1_release.160402-2217

Other people having the same issue:
https://groups.google.com/forum/#!topic/elixir-lang-talk/ea9kIJ4R9ug

**Comment by marciol** [comment]
@nivanson would be nice to improve this issue labeling as a bug.

**Comment by jmerriweather** [comment]
@nivanson yes please label this as a bug, still have the same issue on the latest build 14332

**Comment by benhillis** [comment]
I tried this locally and I'm getting a different error.  Is there additional configuration that I need to do?

```
benhill@BENHILL-X1:~$ sudo mix help
[2016/04/27-00:42:12, critical] Error: Cannot parse configuration file!
[2016/04/27-00:42:12, critical] Terminating Programm!
```

**Comment by jmerriweather** [comment]
that is a different error than i'm getting. Did you follow the install guide for Ubuntu here: http://elixir-lang.org/install.html

I get the following:
```
jm@MGMT-JM-BOOK:~$ mix help
** (ErlangError) erlang error: :terminated
    (stdlib) :io.put_chars(#PID<0.25.0>, :unicode, [[[], "mix app.start         # Starts all registered apps"], 10])
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/tasks/help.ex:51: Mix.Tasks.Help.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by jmerriweather** [comment]
@benhillis Did you have any luck with the install guide? I can't seem to get the same error you've got, perhaps an older version of Elixir? Could you try and run `elixirc -v`

**Comment by benhillis** [comment]
@jmerriweather I tried this just now, it looks like running 'mix help' from my user's home directory works, but I'm getting some odd errors when I try to run from somewhere under /mnt/c.

I'm not at all familiar with mix, are there some other commands I can try?

```
benhill@BENHILL-VM3:~$ elixirc -v
Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.3
benhill@BENHILL-VM3:~$ mix help
mix                   # Runs the default task (current: "mix run")
mix app.start         # Starts all registered apps
mix archive           # Lists all archives
mix archive.build     # Archives this project into a .ez file
mix archive.install   # Installs an archive locally
mix archive.uninstall # Uninstalls archives
mix clean             # Deletes generated application files
mix cmd               # Executes the given command
mix compile           # Compiles source files
mix deps              # Lists dependencies and their status
mix deps.clean        # Deletes the given dependencies' files
mix deps.compile      # Compiles dependencies
mix deps.get          # Gets all out of date dependencies
mix deps.unlock       # Unlocks the given dependencies
mix deps.update       # Updates the given dependencies
mix do                # Executes the tasks separated by comma
mix escript.build     # Builds an escript for the project
mix help              # Prints help information for tasks
mix loadconfig        # Loads and persists the given configuration
mix local             # Lists local tasks
mix local.hex         # Installs Hex locally
mix local.public_keys # Manages public keys
mix local.rebar       # Installs rebar locally
mix new               # Creates a new Elixir project
mix profile.fprof     # Profiles the given file or expression with fprof
mix run               # Runs the given file or expression
mix test              # Runs a project's tests
iex -S mix            # Starts IEx and run the default task
```

**Comment by jmerriweather** [comment]
@benhillis great, that's very exciting! A good test of mix would be setting up a phoenix project
```
mix local.hex
mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
mix phoenix.new hello_world
cd hello_world
mix phoenix.server
```

**Comment by benhillis** [comment]
I see some inotify related failures but it looks like it's working!

![image](https://cloud.githubusercontent.com/assets/17727402/14873497/26d03cb8-0cac-11e6-8127-914e41d7575f.png)

**Comment by jmerriweather** [comment]
@benhillis awesome, thanks Ben! Now to wait for the new build

**Comment by benhillis** [comment]
@jmerriweather I'm not sure if the changes that got this working will be in the next released build, but they will be coming soon™.

**Comment by michallepicki** [comment]
What's the state of this issue? Is it possible to build phoenix apps on the current insider build?

**Comment by olivermt** [comment]
@michallepicki I built and run several phoenix on WSL

**Comment by doughsay** [comment]
If anyone else here has problems, I had some success over here: https://github.com/Microsoft/BashOnWindows/issues/613

**Comment by mogest** [comment]
Recommend this issue be closed.

**Comment by bitcrazed** [comment]
Closing for now. Let us know if you see this problem persist.
