### ISSUE TITLE
Python does not have access to network

### ISSUE THREAD

**Issue by Gingernaut** [Microsoft/BashOnWindows#117]
I'm attempting to run some python Selenium scripts that use Phantomjs. When I run the python script from Powershell the first time, a UAC prompt appears to grant python permission to public and/or private networks, and when granted that permission it works fine. However when I run it from bash, it fails immediately. I suspect it's because bash has no way to prompt a UAC to ask for network permissions, and as a default windows is not allowing my python script to reach out to the network. There needs to be a way to grant network access to programs and processes.

**Comment by sundhaug92** [comment]
Do you have network-access in other, non-python, linux-processes?

**Comment by Gingernaut** [comment]
No, apt-get and SSH both work.

**Comment by tomgrek** [comment]
From the bash command line, this worked for me from the get-go, UAC prompt worked correctly.
`python -m SimpleHTTPServer 8000`

**Comment by pawelmhm** [comment]
I see python has network access ok for me, python-requests work fine. 

```
pawel@PAWEL:~$ cat file.py

import requests
res = requests.get("http://httpbin.org/headers")
print(res.json())

pawel@PAWEL:~$ python file.py
{u'headers': {u'Host': u'httpbin.org', u'Accept-Encoding': u'gzip, deflate', u'Accept': u'*/*', u'User-Agent': u'python-requests/2.10.0'}}
```
But Selenium looks like different story. Main problem I stumbled on is that for some reason firefox fails to start. Selenium installation went fine with pip, I also sudo apt-get installed firefox, and I have following python snippet

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

this fails with 

```
Traceback (most recent call last):
  File "alfa.py", line 4, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

Running firefox from command line fails with:

```
pawel@PAWEL:~$ firefox
Sandbox: unexpected multithreading found; this prevents using namespace sandboxing.
Error: GDK_BACKEND does not match available displays
```

**Comment by benhillis** [comment]
@Gingernaut Have you happened to try this on a more recent build?

**Comment by bitcrazed** [comment]
No activity since July. Closing for now.

**Comment by aseering** [comment]
For what it's worth, I suspect this is/was an issue with PhantomJS (which I believe is WebKit-based so probably suffers from the same failures as are discussed on various other tickets regarding WebKit- and Chrome-based apps).
