### ISSUE TITLE
Node.js local-web-server, http-server and os.networkInterfaces() don't work

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/BashOnWindows#1181]
local-web-server https://www.npmjs.com/package/local-web-server
http-server https://www.npmjs.com/package/http-server

Today I try to use local-web-server and http-server with node.js in WSL. Install this packages globally with following commands

`sudo npm install -g local-web-server`
`sudo npm install -g http-server`

after install is complete when I try to run simple `index.html` file in folder (for test) with this packages I get following errors

Using `local-web-server`

```
user@DESKTOP-TPQIRNP:/mnt/c/Users/User/Desktop/dist$ ws
/usr/lib/node_modules/local-web-server/bin/cli.js:99
  let ipList = Object.keys(os.networkInterfaces())
                              ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Server.onServerUp (/usr/lib/node_modules/local-web-server/bin/cli.js:99:31)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1276:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
```

Using `http-server`

```
user@DESKTOP-TPQIRNP:/mnt/c/Users/User/Desktop/dist$ http-server .
/usr/lib/node_modules/http-server/bin/http-server:14
var ifaces = os.networkInterfaces();
                ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.<anonymous> (/usr/lib/node_modules/http-server/bin/http-server:14:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

When I try to run `os.networkInterfaces()` manually in node terminal I also get error message

```
user@DESKTOP-TPQIRNP:/mnt/c/Users/User/Desktop/dist$ node
> var os = require('os')
undefined
> os.networkInterfaces()
Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:212:10)
    at REPLServer.Interface._line (readline.js:551:8)
>
```

Why is this happening and how to fix it?

**Comment by fpqc** [comment]
Os-networkinterfaces is in the works.  Not sure about the rest.

**Comment by Zx-EvM** [comment]
@fpqc I think I found some explanation. In this issue https://github.com/Microsoft/BashOnWindows/issues/468 but nothing concrete, apart this comment https://github.com/Microsoft/BashOnWindows/issues/468#issuecomment-251298565

**Comment by sunilmut** [comment]
@JasonLinMS as FYI

**Comment by cjibo** [comment]
This is related to os.networkInterface call. I believe this is being worked on. I ran into same thing just using os.networkInterfaces()

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration
