### ISSUE TITLE
setsockopt IPV6_V6ONLY does not work

### ISSUE THREAD

**Issue by anders** [Microsoft/BashOnWindows#128]
````
# python
>>> import socket
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 0)
>>> s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
````

**Comment by hungys** [comment]
Seems the same issue as #68

**Comment by sunilmut** [comment]
@anders Can confirm from our side that the socket option IPPROTO_IPV6\IPV6_V6ONLY is not yet implemented. We have opened a bug on our side to track this. No ETA at this time.

**Comment by russalex** [comment]
Looks to be fixed in 14361:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 0)
>>> s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
>>>
```

**Comment by adcen0107** [comment]
do this
int flag = 1;
int ret = setsockopt(sock_fd, IPPROTO_IPV6, IPV6_V6ONLY, &flag, sizeof(flag));
