### ISSUE TITLE
EISDIR: symlink from symlink of directory with trailing '/' has issues

### ISSUE THREAD

**Issue by stefanpenner** [Microsoft/BashOnWindows#1421]
## A brief description

the following, fails in node on WSL (both not other Ubuntu/OSX)

```js
fs.mkdirSync('out/foo');
fs.writeFileSync('out/foo/bar.txt', 'hi');

fs.symlinkSync(fs.realpathSync('out/foo/'), 'out/bar');
fs.symlinkSync(fs.realpathSync('out/bar/') + '/', 'out/baz'); // the trailing slash here triggers the issue

console.log('out/foo/bar.txt', fs.readFileSync('out/foo/bar.txt', 'UTF8'));
console.log('out/bar/bar.txt', fs.readFileSync('out/bar/bar.txt', 'UTF8'));
console.log('out/baz/bar.txt', fs.readFileSync('out/baz/bar.txt', 'UTF8')); // <-- throws  EISDIR
```

runnable example: https://github.com/stefanpenner/random/blob/master/strange-symlink-issue/index.js

## Expected results

```
hi
hi
hi
```

## Actual results (with terminal output if applicable)

```
out/foo/bar.txt hi
out/bar/bar.txt hi
fs.js:655
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:655:19)
    at tryReadSync (fs.js:456:20)
    at Object.fs.readFileSync (fs.js:493:19)
    at Object.<anonymous> (/home/sam/src/stefanpenner/random/strange-symlink-issue/index.js:27:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

## Your Windows build number

`14393`

## Steps / All commands required to reproduce the error from a brand new installation 

run  https://github.com/stefanpenner/random/blob/master/strange-symlink-issue/index.js in node

##  Strace of the failing command
```
fs.js:655
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:655:19)
    at tryReadSync (fs.js:456:20)
    at Object.fs.readFileSync (fs.js:493:19)
    at Object.<anonymous> (/home/sam/src/stefanpenner/random/strange-symlink-issue/index.js:27:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

## Related:

* ember-cli issue: https://github.com/ember-cli/ember-cli/issues/6338
* symlink work-around: https://github.com/broccolijs/node-symlink-or-copy/pull/29

**Comment by aseering** [comment]
Hi @stefanpenner , thanks for reporting this!  This sounds like an example of #650 , which was fixed in Insider build 14905 (which is newer than the current stable Windows release).

If you're willing to install an [Insider build](https://insider.windows.com), could you test this issue out and see if it's still a problem?  If you think it's a new issue, could you please provide more specifics?

**Comment by stefanpenner** [comment]
> If you're willing to install an Insider build, could you test this issue out and see if it's still a problem?

Sure, downloading the insider stuff now.

**Comment by stefanpenner** [comment]
yup, latest WSL seems to have addressed this.
