### ISSUE TITLE
All requests made within nodejs time out

### ISSUE THREAD

**Issue by Plazmaz** [Microsoft/BashOnWindows#1697]
* A brief description
I've run into an interesting issue that didn't occur in previous versions of WSL. Whenever ANY network request is made from nodejs, it either times out or throws one of two other errors I can't find information on.
* Expected results
When making a request to google or another stable site a response should be returned

* Actual results (with terminal output if applicable)
Seemingly randomly one of three results:
```
Error: connect EBADF 216.58.217.4:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at connect (net.js:884:16)
    at emitLookup (net.js:1013:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```
```
Error: connect ETIMEDOUT 216.58.217.4:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at connect (net.js:884:16)
    at emitLookup (net.js:1013:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```
or
```
Error: connect Unknown system error -25 216.58.217.4:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at connect (net.js:884:16)
    at emitLookup (net.js:1013:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```
* Your Windows build number
15031.rs2_release.170204-1546

* Steps / All commands required to reproduce the error from a brand new installation 
```
node
https.get("https://www.google.com", function(err, res) { if(err) {console.log(err)} else{ console.log(res) }})
```

* Required packages and commands to install
nodejs, npm
`sudo apt-get install nodejs npm`

**Comment by byronpolley** [comment]
I second this however I'm not even getting an error besides in the log. My bash terminal just freezes and then black screens upon reopening until I restart. Any command with npm does this.

**Comment by NiluK** [comment]
Yeah, same issue for me too. Running Webpack's HMR - initial bundle appears to work fine, but the entire script just freezes after modifying a file.

**Comment by benhillis** [comment]
This is probably #1675.

**Comment by byronpolley** [comment]
I cannot get a basic Angular package to run that's been cloned off Git. It uses npm start to trigger npm install and bower install. Also gets stuck at server initialization. If this is full featured and no bugs after beta I'll be so happy, that and tabs :P

**Comment by gurpreetatwal** [comment]
Could this be the same issue as #1683?

**Comment by benhillis** [comment]
@gurpreetatwal - I think it is likely.

**Comment by Dj-jom2x** [comment]
fixed ^_^ 15042 build
