### ISSUE TITLE
Java file access with separator

### ISSUE THREAD

**Issue by tz1010** [Microsoft/BashOnWindows#1703]
I try to run a maven build with java on WSL including a code quality tool which generates some files during the build. The build fails while creating a file on the windows mount.

I know the problem is the wrong path separator `:` which is the UNIX separator. This separator is selected during the build by the environment the build runs on.

* Expected results
I would expect that WSL can handle such separator. I guess the problem here is the file access through the windows mount but can not this be parsed during file access?

* Actual results
```
Caused by: java.io.FileNotFoundException: /mnt/d/dev/commons/commons-utils/target/classes:findbug_excludes_171794724455000.xml (Das Argument ist ungültig)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:367)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1962)
        at com.qulice.findbugs.FindBugsValidator.excludes(FindBugsValidator.java:166)
        ... 26 more
```

* Windows build number
14393.693

* Steps / All commands required to reproduce the error from a brand new installation 
To reproduce this bug it's enough to create a new `FileOutputStream` (Java app) with a filename include a `:` separator on the windows mount filesystem.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  This is the same as #1514 so closing it out as a duplicate.  Creating the file should work fine from lxfs but please let us know if you hit any issues.
