### ISSUE TITLE
env command says it cannot allocate memory

### ISSUE THREAD

**Issue by petropolis** [Microsoft/BashOnWindows#1734]
* A brief description
The "env" command spawned by maven-javadoc-plugin says it "Cannot allocate memory"

* Expected results
Shouldn't fail with a memory error

* Actual results (with terminal output if applicable)
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:javadoc (generate-service-docs) on project service: An error has occurred in JavaDocs report generation: Unable to execute javadoc command: Error setting up environmental variables: Cannot run program "env": error=12, Cannot allocate memory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:javadoc (generate-service-docs) on project service: An error has occurred in JavaDocs report generation: Unable to execute javadoc command: Error setting up environmental variables
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JavaDocs report generation: Unable to execute javadoc command: Error setting up environmental variables
        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.failOnError(AbstractJavadocMojo.java:5777)
        at org.apache.maven.plugin.javadoc.JavadocReport.execute(JavadocReport.java:315)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more

* Your Windows build number
10.0.14393 Build 14393

* Steps / All commands required to reproduce the error from a brand new installation 
Not quite sure what parameters are being used. I'd look at the maven javadoc plugin source code (https://maven.apache.org/plugins/maven-javadoc-plugin/) and the env source code to see what system calls it is executing.

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Probably #1286. Either make a very large page file as a work-around, upgrade to [Insider Builds](https://insider.windows.com/), or wait a little bit for the Creators update.

**Comment by aseering** [comment]
For what it's worth, I would be amazed if the `env` command itself used very much memory, but it is usually used as a way to launch other commands within a particular environment.  I suspect that what might actually be happening is that whatever command `env` is attempting to launch, is the command that's actually running out of memory and failing.

But, yeah, @therealkenc +1.  A lot of memory-related issues have been fixed there.

**Comment by benhillis** [comment]
Agreed with @therealkenc, this is likely #1286. I'll try to reproduce this on a recent build.

**Comment by petropolis** [comment]
![page_size](https://cloud.githubusercontent.com/assets/6721444/23484310/53d26afc-fe8b-11e6-8136-b28e786cdb69.png)

My system page size is 8 gig (far larger than I need). Shouldn't that be sufficient?

**Comment by therealkenc** [comment]
@petropolis - Try kicking it up to 16000MB (16GB) if you have the the disk space. Per #1286, 5GB, with is plenty "sufficient" too, doesn't cut it either. I don't know where the magic number lies; or even if the magic number is a constant. But as the title says, it needs to be "excessively large". In that issue the [test case](https://gist.github.com/therealkenc/9df8855404fa4d74488a053b0004627b) is just spawning "echo".

**Comment by benhillis** [comment]
This should be fixed in Creators Update. Please reopen if you continue to see this issue.

**Comment by alamantia** [comment]
This is happening to me even on the latest release a year later (even with with a huge page file)
