### ISSUE TITLE
var networkInterfaces = require("os").networkInterfaces();  ^ Error: EINVAL, invalid argument

### ISSUE THREAD

**Issue by ahmetcadirci25** [Microsoft/BashOnWindows#1847]
My repo 

[https://github.com/ahmetcadirci25/browsersync-gulp-sass](https://github.com/ahmetcadirci25/browsersync-gulp-sass)

**$ gulp**

```
Error: EINVAL, invalid argument
    at getIp (/home/ahmet/browsersync-gulp-sass/node_modules/browser-sync/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/home/ahmet/browsersync-gulp-sass/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ahmet/browsersync-gulp-sass/node_modules/browser-sync/lib/snippet.js:9:20)
    at Module._compile (module.js:456:26)
```

![ekran alintisi](https://cloud.githubusercontent.com/assets/9280397/24587622/a871141e-17c2-11e7-8833-ec4777dc98da.PNG)

**$ lsb_release -a**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**$ node -v**
```
v0.10.25
```
**$ sass -v**
```
Sass 3.2.12 (Media Mark)
```
**$ gulp -v**
```
[16:35:12] CLI version 3.9.1
[16:35:12] Local version 3.9.1
```

**Comment by therealkenc** [comment]
See #468. This is implemented on [Insider Builds](https://blogs.windows.com/blog/tag/windows-insider-program/), or sit tight for Creators Update.

**Comment by devgtorres** [comment]
put this in your compiler's config file.
require('os').networkInterfaces() } catch (e) { require('os').networkInterfaces = () => ({}) }

**Comment by Vinlock** [comment]
I'm not understanding where to put this for React :(. I tried webpack config and index.js and devserver config too... T-T
