### ISSUE TITLE
Unable to Translate Current Working Directory

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/BashOnWindows#2011]
**Microsoft Windows [Version 10.0.16179]**

## Commands

`code .`
`code-insiders .`
`docker-compose.exe --help`

## Problem

Get the following error when attempting to open VS Code, VS Code Insiders, or interact with Docker-Compose (standard Docker for Windows installation). There is no issues running `docker` (e.g. `docker.exe`) commands, though.

 - Error: `Unable to translate current working directory. Using C:\WINDOWS\system32` 

Of all these issues, Docker Compose is the most important. 

## Strace

```
execve("/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe", ["docker-compose.exe", "--help"], [/* 15 vars */]) = 0
brk(NULL)                               = 0x7ffff792f000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff67af00000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24973, ...}) = 0
mmap(NULL, 24973, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff67aef9000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff67a830000
mprotect(0x7ff67a9ef000, 2097152, PROT_NONE) = 0
mmap(0x7ff67abef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7ff67abef000
mmap(0x7ff67abf5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff67abf5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff67aef0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff67aee0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff67aed0000
arch_prctl(ARCH_SET_FS, 0x7ff67aee0700) = 0
mprotect(0x7ff67abef000, 16384, PROT_READ) = 0
mprotect(0x7ff67b20a000, 4096, PROT_READ) = 0
mprotect(0x7ff67ae25000, 4096, PROT_READ) = 0
munmap(0x7ff67aef9000, 24973)           = 0
getpid()                                = 31
brk(NULL)                               = 0x7ffff792f000
brk(0x7ffff7950000)                     = 0x7ffff7950000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1668976, ...}) = 0
mmap(NULL, 1668976, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff67ac8d000
close(3)                                = 0
getcwd("/home/bojeda", 4096)            = 13
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7ffffe9e5550) = 0
open("/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe", O_RDONLY) = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7ffffe9e5400) = 0
close(5)                                = 0
open("/home/bojeda", O_RDONLY)          = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7ffffe9e5400) = -1 EINVAL (Invalid argument)
close(5)                                = 0
ioctl(4, _IOC(0, 0x00, 0x97, 0x22), 0x7ffffe9e54b0) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7ffffe9e54a8) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7ffffe9e54a8) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7ffffe9e54a8) = 0
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\320\0\0\0\0\0\0\0"..., 224) = 224
read(4, "\0\0\0\0\0\0\0\0\240\0\0\0\0\0\0\0", 16) = 16
ioctl(4, _IOC(0, 0x00, 0x9b, 0x22), 0x7ffffe9e5548) = 0
write(4, "\0\0\0\0\0\0\0\0\240\0\0\0\0\0\0\0", 16) = 16
ioctl(5, _IOC(0, 0x00, 0xbf, 0x22), 0x7ffffe9e5540) = 0
close(3)                                = 0
close(4)                                = 0
close(5)                                = 0
exit_group(-1)                          = ?
+++ exited with 255 +++
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
@sgtoj - What current working directory are you working out of? This warning message is letting you know you're working out of a directory that should not be accessed via NT processes (for example your /home/username directory).

**Comment by sgtoj** [comment]
I have tried from multiple places. 
  - /home/me
  - /test  (777 permissions)
  - /mnt/c/Program Files/Docker/Docker/resources/bin

In addition to the previous error, there error was returned too.

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 66, in main
  File "compose\cli\main.py", line 98, in dispatch
  File "compose\cli\docopt_command.py", line 25, in parse
  File "compose\cli\docopt_command.py", line 12, in docopt_full_help
  File "site-packages\docopt.py", line 575, in docopt
  File "site-packages\docopt.py", line 481, in extras
LookupError: unknown encoding: cp65001
Failed to execute script docker-compose
```

## Strace

```
execve("/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe", ["docker-compose.exe", "--help"], [/* 16 vars */]) = 0
brk(NULL)                               = 0x7fffb8bf6000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f07f6c00000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24973, ...}) = 0
mmap(NULL, 24973, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f07f6bf9000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f07f6430000
mprotect(0x7f07f65ef000, 2097152, PROT_NONE) = 0
mmap(0x7f07f67ef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f07f67ef000
mmap(0x7f07f67f5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f07f67f5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f07f6bf0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f07f6be0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f07f6bd0000
arch_prctl(ARCH_SET_FS, 0x7f07f6be0700) = 0
mprotect(0x7f07f67ef000, 16384, PROT_READ) = 0
mprotect(0x7f07f700a000, 4096, PROT_READ) = 0
mprotect(0x7f07f6a25000, 4096, PROT_READ) = 0
munmap(0x7f07f6bf9000, 24973)           = 0
getpid()                                = 65
brk(NULL)                               = 0x7fffb8bf6000
brk(0x7fffb8c17000)                     = 0x7fffb8c17000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1668976, ...}) = 0
mmap(NULL, 1668976, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f07f6a38000
close(3)                                = 0
getcwd("/mnt/c/Program Files/Docker/Docker/resources/bin", 4096) = 49
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7fffbfe49780) = 0
open("/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe", O_RDONLY) = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffbfe49630) = 0
close(5)                                = 0
open("/mnt/c/Program Files/Docker/Docker/resources/bin", O_RDONLY) = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffbfe49630) = 0
close(5)                                = 0
ioctl(4, _IOC(0, 0x00, 0x97, 0x22), 0x7fffbfe496e0) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffbfe496d8) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffbfe496d8) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffbfe496d8) = 0
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\342\0\0\0\0\0\0\0"..., 268) = 268
read(4, "\0\0\0\0\0\0\0\0\255\0\0\0\0\0\0\0", 16) = 16
ioctl(4, _IOC(0, 0x00, 0x9b, 0x22), 0x7fffbfe49778) = 0
write(4, "\0\0\0\0\0\0\0\0\255\0\0\0\0\0\0\0", 16) = 16
ioctl(5, _IOC(0, 0x00, 0xbf, 0x22), 0x7fffbfe49770) = 0
close(3)                                = 0
close(4)                                = 0
close(5)                                = 0
exit_group(-1)                          = ?
+++ exited with 255 +++
```

**Comment by CherryDT** [comment]
For `/home/me` and `/test`, this is expected, because there is no valid Windows-side equivalent for these paths which could be used as working directory for VSCode, see https://github.com/Microsoft/BashOnWindows/issues/2004

What's surprising me is `/mnt/c/Program Files/Docker/Docker/resources/bin` because this one _should_ work (there is a Window equivalent: `C:\Program Files\Docker\Docker\resources\bin`).

As for the cp65001 problem, you seem to be hitting https://github.com/Microsoft/BashOnWindows/issues/2009

**Comment by sgtoj** [comment]
@CherryDT Excellent! That's useful information. I will look at those linked issues a little deeper tonight.

Ideally, I would be working out of my Windows' user directory, so `/mnt/c/Users/me/...`. Basically, the use case (or story) is to be able to use **Docker for Windows'** Docker Client and Docker Compose interface from Bash, along with python, npm, node, etc, during development. 

Currently, I have to switch back and forth between PowerShell (for docker commands) and Bash for npm. This is the problem I am trying to solve.

**Comment by sgtoj** [comment]
Now that I understand the problem is encoding related. I am not sure if this an issue with the Windows Console, WSL, Python, or Docker Compose (which is compiled Py 2/3 code)?

**Comment by sunjoong** [comment]
@sgtoj - I'm not sure that is encoding issue, but if encoding issue... I'll begin to compair in these three casese; 1. in bash throuh bash shortcut in start menu 2. in bash through bash command in cmd 3. in just cmd. I have no idea about docker, so it's an idea. It looks like a windows program of "C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe". If it's good in case 3 and 2 but fail in case 1, it might be encoding issue because locale, i.e., codepage of case 2 and 1 are different but they are bash.

**Comment by sgtoj** [comment]
So I should point out that @CherryDT has informed of the cause for the original issue with the pathing error. Turns out the issue is caused by  VS Code or Docker Compose Client (Win32 apps) was trying to access a Linux only path. If the current directory is a common directory between both Windows and Linux (e.g. /mnt/c/Users/me <--> C:\Users\me), the pathing error goes away.

He also point out my second error (`LookupError: unknown encoding: cp65001`) is an encoding issue that matches #2009.  My latest reply was in regard of the latter issue.  Therefore, I will close this ticket and re-post my encoding question to #2009.

**Comment by mqudsi** [comment]
This error is generated by the WSL subsystem and cannot be worked around from within a win32 binary (it happens before the binary is executed). The only solution is to use a wrapper script or program to call the intended binary, filtering the stderr output as needed.

Here is my example wslnoerr.sh:

```
#!/bin/bash
app=$1
shift
$1 "$@" 2> >(sed -e '1h;2,$H;$!d;g' -r -e 's/Unable to translate[^\n]*\n//' 1>&2)
```

Usage: `./wslnoerr.sh target`
