### ISSUE TITLE
Creating UDP sockets in Java 8 throws exception on WSL

### ISSUE THREAD

**Issue by jordansissel** [Microsoft/BashOnWindows#2111]
* Your Windows build number:  Microsoft Windows [Version 10.0.14393]

```
% java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

* What you're doing and what's happening:  Running java app that tries to do a DNS lookup.

Minimal reproduction:

```java

import java.net.DatagramSocket;

public class X {
  public static void main(String[] args) throws Exception {
    DatagramSocket x = new DatagramSocket();
  }
}
```

`javac X.java; java X` will reproduce.

* What's wrong / what should be happening instead: Creating socket initialization in java is crashing due to a failed setsockopt:

```
% java X
Exception in thread "main" java.net.SocketException: Invalid argument
        at java.net.PlainDatagramSocketImpl.datagramSocketCreate(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.create(AbstractPlainDatagramSocketImpl.java:80)
        at java.net.DatagramSocket.createImpl(DatagramSocket.java:337)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:239)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:196)
        at X.main(X.java:6)
```

* Strace of the failing command, if applicable: 

```
[pid  2048] socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 4
[pid  2048] setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
[pid  2048] setsockopt(4, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid  2048] setsockopt(4, SOL_IPV6, 0x31 /* IPV6_??? */, [0], 4) = -1 EINVAL (Invalid argument)
Exception in thread "main" java.net.SocketException: Invalid argument
        at java.net.PlainDatagramSocketImpl.datagramSocketCreate(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.create(AbstractPlainDatagramSocketImpl.java:80)
        at java.net.DatagramSocket.createImpl(DatagramSocket.java:337)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:239)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:196)
```

**Comment by aseering** [comment]
Hi @jordansissel -- thanks for posting!  Would you be willing/able to try this on the Windows Creators update (the latest version of Windows 10)?  A *lot* of networking improvements/fixes went in between the Anniversary release (which you're using) and the Creators release.

**Comment by therealkenc** [comment]
> [pid  2048] setsockopt(4, SOL_IPV6, 0x31 /* IPV6_??? */, [0], 4) = -1 EINVAL (Invalid argument)

#674 and friends, fixed in 14936. You should be good on Creators.

**Comment by sunilmut** [comment]
@jordansissel - Thanks for the post. Thanks @aseering and @therealkenc for the triage. To be precise, IPV6 option 0x31 is `IPV6_RECVPKTINFO`, which was fixed in [15007](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15007). Moving to Creators Update (CU) as suggested above would be the best option.

**Comment by jordansissel** [comment]
I am unsuccessful in upgrading at this time, but I am glad to hear this issue is already fixed. Nice work! :)

**Comment by jordansissel** [comment]
Confirmed this no longer fails on windows version 10.0.15063

**Comment by sunilmut** [comment]
@jordansissel - Thanks for the confirmation and please keep the feedback coming.
