### ISSUE TITLE
gradle not working on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by JesseBoulard** [Microsoft/BashOnWindows#2189]
Trying to run gradle on bash on Ubuntu on Windows has been a nightmare, wasting dozens of hours trying to find a workaround. I just reinstalled BoUoW today and installed java and gradle with sdkman. Here's the error with stacktrace:

jesse@DESKTOP-LNO2BVT:~/.sdkman/candidates/gradle/current/bin$ gradle init --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine a usable local IP for this machine.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.RuntimeException: Could not determine a usable local IP for this machine.
        at org.gradle.internal.remote.internal.inet.InetAddressFactory.getLocalBindingAddress(InetAddressFactory.java:89)
        at org.gradle.cache.internal.FileLockCommunicator.<init>(FileLockCommunicator.java:38)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:153)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:145)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:85)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:73)
        at org.gradle.cache.internal.OnDemandFileAccess.readFile(OnDemandFileAccess.java:36)
        at org.gradle.cache.internal.SimpleStateCache.get(SimpleStateCache.java:47)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.get(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:31)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getAll(PersistentDaemonRegistry.java:69)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:112)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:127)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:81)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:281)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:254)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:247)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.net.SocketException: Cannot assign requested address (ioctl SIOCGIFNETMASK failed)
        at java.net.NetworkInterface.getAll(Native Method)
        at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
        at org.gradle.internal.remote.internal.inet.InetAddresses.analyzeNetworkInterfaces(InetAddresses.java:48)
        at org.gradle.internal.remote.internal.inet.InetAddresses.<init>(InetAddresses.java:40)
        at org.gradle.internal.remote.internal.inet.InetAddressFactory.init(InetAddressFactory.java:100)
        at org.gradle.internal.remote.internal.inet.InetAddressFactory.getLocalBindingAddress(InetAddressFactory.java:85)
        ... 31 more

**Comment by sunjoong** [comment]
@JesseBoulard - #850 or #773?

**Comment by JesseBoulard** [comment]
I read both of those and they don't seem to apply to me. I'm not a Windows
insider. I just have the latest updated version of Windows. If I became a
Windows insider would that solve my problem?

**Comment by sunjoong** [comment]
@JesseBoulard - The lastest comment https://github.com/Microsoft/BashOnWindows/issues/850#issuecomment-297775330 mentioned about  Creator's update and after then WSL update, not a insider preview version but a public version, windows 10 version 1703. The lastest build number of 1703 is 15063; You can see it using `ver` comand in cmd.exe window like `Microsoft Windows [Version 10.0.15063]` and this information was asked in template when you opened this issue.

**Comment by JesseBoulard** [comment]
Thanks a lot, I guess I was so ignorant about this that I assumed Windows
automatically updated. I'm running build 14393.1198. Downloading upgrade
now. So do you think that will fix the problem?

**Comment by sunjoong** [comment]
@JesseBoulard - 14393 is the lastes build number of version 1607 (Redstone1), not version 1703 (Redstore 2). Hmm....

I think.... https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant may help you to update from Redstone1 to Redston2.
* https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update
* http://www.windowscentral.com/how-get-windows-10-creators-update
* http://www.thewindowsclub.com/windows-10-upgrade-assistant

**Comment by JesseBoulard** [comment]
solved, thanks so much for rescuing my brain :)
