### ISSUE TITLE
pyserial hangs when writing due to select call

### ISSUE THREAD

**Issue by thomasbrandon** [Microsoft/BashOnWindows#2231]
**Version:** Microsoft Windows [Version 10.0.16215.1000]

Running a python script using pyserial's write function hangs under bash on windows must be terminated with ^C. Running under python on windows succeeds. This report is using the current pip version of pyserial v3.3 (same results under pyserial 3.0.1). The issue happens both with a connected USB-Serial converter and with a motherboard serial port with no connected device. 

## Bash output
```
$ python serialwrite.py /dev/ttyS3
Opening port: /dev/ttyS3
Writing...
^CTraceback (most recent call last):
  File "serialwrite.py", line 7, in <module>
    ser.write('test')
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 553, in write
    abort, ready, _ = select.select([self.pipe_abort_write_r], [self.fd], [], None)
KeyboardInterrupt
```
## Windows output
```
>python serialwrite.py COM3
Opening port: COM3
Writing...
Written.
```
## Bash setup
```
# sudo apt install python python-pip
# pip install pyserial
# sudo chmod 666 /dev/ttyS3
# stty -F /dev/ttyS3 sane 115200
```
## Python test script (serialwrite.py)
```python
import sys, serial
port = sys.argv[1]
print "Opening port: " + port
with serial.Serial(port, 115200) as ser:
  print "Writing..."
  ser.write('test')
  print "Written."
```
## strace output (after python load)
```
write(1, "Opening port: /dev/ttyS3\n", 25Opening port: /dev/ttyS3) = 25
open("/dev/ttyS3", O_RDWR|O_NOCTTY|O_NONBLOCK) = 3
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, SNDCTL_TMR_START or TCSETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TIOCMBIS, [TIOCM_DTR])         = 0
ioctl(3, TIOCMBIS, [TIOCM_RTS])         = 0
ioctl(3, TCFLSH, TCIFLUSH)              = 0
pipe([4, 5])                            = 0
pipe([6, 7])                            = 0
fcntl(4, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
fcntl(6, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
write(1, "Writing...\n", 11Writing...
)            = 11
write(3, "test", 4)                     = 4
select(7, [6], [3], [], NULL
^C
strace: Process 7266 detached
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Comparing against native Linux it looks like the initial epoll state is incorrect and should be easy to fix up.  The fix should make it out to insider builds soon.

**Comment by benhillis** [comment]
Fixed in 16237.

**Comment by thomasbrandon** [comment]
Can confirm this fixes my issue and the pyserial based tool I was trying (esptool.py, a flasher for the ESP32 processor) now works, at least for the functions I've tested.

Thanks all.
