### ISSUE TITLE
Apache Spark Shell Error when running Windows 10 Ubuntu Bash

### ISSUE THREAD

**Issue by anandrajj** [Microsoft/BashOnWindows#2317]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  I run apache_spark_1.6/bin/spark-shell, I get the java.net.SocketException:  error.

* What's wrong / what should be happening instead: Spark must have started the console with SparkContext and SQLContext created.

* Strace of the failing command, if applicable:  java.net.SocketException: Cannot assign requested address (ioctl SIOCGIFNETMASK failed)
        at java.net.NetworkInterface.getAll(Native Method)
        at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
        at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:796)
        at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:782)
        at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:782)
        at org.apache.spark.util.Utils$$anonfun$localHostNameForURI$1.apply(Utils.scala:846)
        at org.apache.spark.util.Utils$$anonfun$localHostNameForURI$1.apply(Utils.scala:846)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.util.Utils$.localHostNameForURI(Utils.scala:846)
        at org.apache.spark.HttpServer.uri(HttpServer.scala:163)
        at org.apache.spark.repl.SparkIMain.classServerUri(SparkIMain.scala:141)
        at org.apache.spark.repl.SparkILoop.createSparkContext(SparkILoop.scala:1012)
        at $iwC$$iwC.<init>(<console>:15)
        at $iwC.<init>(<console>:24)
        at <init>(<console>:26)
        at .<init>(<console>:30)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sunjoong** [comment]
@anandrajj - #1477?

**Comment by anandrajj** [comment]
Thanks. After updating Window 10 to build 15063. Spark 1.6.3 worked straight of the box.  

@sunjoong Thanks for your reply!!
