### ISSUE TITLE
Cannot install with npm (nodejs v5)

### ISSUE THREAD

**Issue by tejinderss** [Microsoft/BashOnWindows#257]
Getting error "cannot rename /root/npm_modules/xxx"

**Comment by tejinderss** [comment]
seems to be fixed on latest build

**Comment by dimitrovs** [comment]
This is still a problem for me with the latest build. See this gist: https://gist.github.com/rangedsp/7eceb320fea00b344dbdd17cd154cdef

**Comment by davidmaxwaterman** [comment]
I find the same, except with nothing else running (fresh boot, straight into bash) :

```
maxw@~$ mkdir tmp
maxw@~$ cd tmp
maxw@tmp$ git clone https://github.com/Polymer/polymer-build
Cloning into 'polymer-build'...
remote: Counting objects: 4307, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 4307 (delta 32), reused 2 (delta 2), pack-reused 4231
Receiving objects: 100% (4307/4307), 19.15 MiB | 2.16 MiB/s, done.
Resolving deltas: 100% (2228/2228), done.
Checking connectivity... done.
maxw@tmp$ cd polymer-build/
maxw@polymer-build$ nvm current
v7.6.0
maxw@polymer-build$ node --version
v7.6.0
maxw@polymer-build$ npm --version
4.1.2
maxw@polymer-build$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
polymer-build@0.8.2 /home/maxw/tmp/polymer-build
├── @types/chai@3.4.35
├─┬ @types/fs-extra@0.0.37
│ └── @types/node@7.0.5
├── @types/mocha@2.2.39
├── @types/parse5@2.2.34
├── @types/sinon@1.16.35
├── @types/vinyl@1.2.30
├─┬ @types/vinyl-fs@0.0.28
│ └─┬ @types/glob-stream@3.1.30
│   └─┬ @types/glob@5.0.30
│     └── @types/minimatch@2.0.29
├─┬ chai@3.5.0
│ ├── assertion-error@1.0.2
│ ├─┬ deep-eql@0.1.3
│ │ └── type-detect@0.1.1
│ └── type-detect@1.0.0
├─┬ clang-format@1.0.45
│ ├── async@1.5.2
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ └─┬ resolve@1.3.2
│   └── path-parse@1.0.5
├─┬ del@2.2.2
│ ├─┬ globby@5.0.0
│ │ ├── array-union@1.0.2
│ │ └── arrify@1.0.1
│ ├── is-path-cwd@1.0.0
│ ├─┬ is-path-in-cwd@1.0.0
│ │ └─┬ is-path-inside@1.0.0
│ │   └── path-is-inside@1.0.2
│ ├── object-assign@4.1.1
│ ├── pify@2.3.0
│ ├─┬ pinkie-promise@2.0.1
│ │ └── pinkie@2.0.4
│ └── rimraf@2.6.1
├─┬ depcheck@0.6.7
│ ├─┬ babel-traverse@6.23.1
│ │ ├── babel-messages@6.23.0
│ │ ├─┬ babel-runtime@6.23.0
│ │ │ ├── core-js@2.4.1
│ │ │ └── regenerator-runtime@0.10.3
│ │ ├─┬ babel-types@6.23.0
│ │ │ └── to-fast-properties@1.0.2
│ │ ├─┬ debug@2.6.1
│ │ │ └── ms@0.7.2
│ │ ├── globals@9.16.0
│ │ └─┬ invariant@2.2.2
│ │   └── loose-envify@1.3.1
│ ├── babylon@6.16.1
│ ├── builtin-modules@1.1.1
│ ├── deprecate@1.0.0
│ ├── deps-regex@0.1.4
│ ├─┬ js-yaml@3.8.1
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@3.1.3
│ ├── lodash@4.17.4
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ ├── require-package-name@2.0.1
│ ├── walkdir@0.0.11
│ └─┬ yargs@6.6.0
│   ├── camelcase@3.0.0
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.1.0
│   ├── decamelize@1.2.0
│   ├── get-caller-file@1.0.2
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ └── path-exists@2.1.0
│   │ └─┬ read-pkg@1.1.0
│   │   ├── load-json-file@1.1.0
│   │   └── path-type@1.1.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── set-blocking@2.0.0
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ └── is-fullwidth-code-point@1.0.0
│   ├── which-module@1.0.0
│   ├── y18n@3.2.1
│   └─┬ yargs-parser@4.2.1
│     └── camelcase@3.0.0
├─┬ dom5@2.1.0
│ ├── @types/clone@0.1.30
│ ├── @types/node@6.0.63
│ └── clone@2.1.0
├─┬ fs-extra@2.0.0
│ ├── graceful-fs@4.1.11
│ └── jsonfile@2.4.0
├─┬ gulp@3.9.1
│ ├── archy@1.0.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├── deprecated@0.0.1
│ ├─┬ gulp-util@3.0.8
│ │ ├── array-differ@1.0.0
│ │ ├── array-uniq@1.0.3
│ │ ├── beeper@1.1.1
│ │ ├── dateformat@2.0.0
│ │ ├─┬ fancy-log@1.3.0
│ │ │ └── time-stamp@1.0.1
│ │ ├─┬ gulplog@1.0.0
│ │ │ └── glogg@1.0.0
│ │ ├─┬ has-gulplog@0.1.0
│ │ │ └── sparkles@1.0.0
│ │ ├── lodash._reescape@3.0.0
│ │ ├── lodash._reevaluate@3.0.0
│ │ ├── lodash._reinterpolate@3.0.0
│ │ ├─┬ lodash.template@3.6.2
│ │ │ ├── lodash._basecopy@3.0.1
│ │ │ ├── lodash._basetostring@3.0.1
│ │ │ ├── lodash._basevalues@3.0.0
│ │ │ ├─┬ lodash.escape@3.2.0
│ │ │ │ └── lodash._root@3.0.1
│ │ │ ├─┬ lodash.keys@3.1.2
│ │ │ │ ├── lodash._getnative@3.9.1
│ │ │ │ ├── lodash.isarguments@3.1.0
│ │ │ │ └── lodash.isarray@3.0.4
│ │ │ ├── lodash.restparam@3.6.1
│ │ │ └── lodash.templatesettings@3.1.1
│ │ ├── minimist@1.2.0
│ │ ├─┬ multipipe@0.1.2
│ │ │ └─┬ duplexer2@0.0.2
│ │ │   └─┬ readable-stream@1.1.14
│ │ │     └── isarray@0.0.1
│ │ ├── object-assign@3.0.0
│ │ └─┬ vinyl@0.5.3
│ │   └── clone@1.0.2
│ ├── interpret@1.0.1
│ ├─┬ liftoff@2.3.0
│ │ ├── extend@3.0.0
│ │ ├─┬ findup-sync@0.4.3
│ │ │ ├─┬ detect-file@0.1.0
│ │ │ │ └── fs-exists-sync@0.1.0
│ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ └── is-extglob@1.0.0
│ │ │ └─┬ resolve-dir@0.1.1
│ │ │   └─┬ global-modules@0.2.3
│ │ │     └─┬ global-prefix@0.1.5
│ │ │       ├─┬ homedir-polyfill@1.0.1
│ │ │       │ └── parse-passwd@1.0.0
│ │ │       └─┬ which@1.2.12
│ │ │         └── isexe@1.1.2
│ │ ├─┬ fined@1.0.2
│ │ │ ├── expand-tilde@1.2.2
│ │ │ ├── lodash.assignwith@4.2.0
│ │ │ ├── lodash.isempty@4.4.0
│ │ │ ├── lodash.pick@4.4.0
│ │ │ └─┬ parse-filepath@1.0.1
│ │ │   ├── map-cache@0.2.2
│ │ │   └─┬ path-root@0.1.1
│ │ │     └── path-root-regex@0.1.2
│ │ ├── flagged-respawn@0.3.2
│ │ ├── lodash.isplainobject@4.0.6
│ │ ├── lodash.isstring@4.0.1
│ │ ├── lodash.mapvalues@4.6.0
│ │ └── rechoir@0.6.2
│ ├── minimist@1.2.0
│ ├─┬ orchestrator@0.3.8
│ │ ├─┬ end-of-stream@0.1.5
│ │ │ └── once@1.3.3
│ │ ├── sequencify@0.0.7
│ │ └── stream-consume@0.1.0
│ ├── pretty-hrtime@1.0.3
│ ├── semver@4.3.6
│ ├─┬ tildify@1.2.0
│ │ └── os-homedir@1.0.2
│ ├─┬ v8flags@2.0.11
│ │ └── user-home@1.1.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ defaults@1.0.3
│   │ └── clone@1.0.2
│   ├─┬ glob-stream@3.1.18
│   │ ├── glob@4.5.3
│   │ ├─┬ glob2base@0.0.12
│   │ │ └── find-index@0.1.1
│   │ ├── minimatch@2.0.10
│   │ ├── ordered-read-streams@0.1.0
│   │ └── unique-stream@1.0.0
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     ├─┬ glob@3.1.21
│   │     │ ├── graceful-fs@1.2.3
│   │     │ └── inherits@1.0.2
│   │     ├── lodash@1.0.2
│   │     └─┬ minimatch@0.2.14
│   │       ├── lru-cache@2.7.3
│   │       └── sigmund@1.0.1
│   ├─┬ graceful-fs@3.0.11
│   │ └── natives@1.1.0
│   ├── strip-bom@1.0.0
│   ├─┬ through2@0.6.5
│   │ └─┬ readable-stream@1.0.34
│   │   └── isarray@0.0.1
│   └─┬ vinyl@0.4.6
│     └── clone@0.2.0
├─┬ gulp-spawn-mocha@3.1.0
│ └── through@2.3.8
├─┬ gulp-tslint@7.1.0
│ └── map-stream@0.1.0
├─┬ gulp-typescript@3.1.5
│ ├── source-map@0.5.6
│ └─┬ through2@2.0.3
│   └── xtend@4.0.1
├─┬ gulp-typings@2.0.4
│ ├─┬ typings-core@1.6.1
│ │ ├── any-promise@1.3.0
│ │ ├─┬ configstore@2.1.0
│ │ │ ├─┬ dot-prop@3.0.0
│ │ │ │ └── is-obj@1.0.1
│ │ │ ├── osenv@0.1.4
│ │ │ ├── uuid@2.0.3
│ │ │ └─┬ write-file-atomic@1.3.1
│ │ │   ├── imurmurhash@0.1.4
│ │ │   └── slide@1.1.6
│ │ ├─┬ detect-indent@4.0.0
│ │ │ └─┬ repeating@2.0.1
│ │ │   └── is-finite@1.0.2
│ │ ├─┬ has@1.0.1
│ │ │ └── function-bind@1.1.0
│ │ ├─┬ is-absolute@0.2.6
│ │ │ ├─┬ is-relative@0.2.1
│ │ │ │ └─┬ is-unc-path@0.1.2
│ │ │ │   └── unc-path-regex@0.1.2
│ │ │ └── is-windows@0.2.0
│ │ ├── listify@1.0.0
│ │ ├── lockfile@1.0.3
│ │ ├─┬ make-error-cause@1.2.2
│ │ │ └── make-error@1.2.1
│ │ ├─┬ object.pick@1.2.0
│ │ │ └── isobject@2.1.0
│ │ ├─┬ parse-json@2.2.0
│ │ │ └─┬ error-ex@1.3.0
│ │ │   └── is-arrayish@0.2.1
│ │ ├─┬ popsicle@8.2.0
│ │ │ ├─┬ concat-stream@1.6.0
│ │ │ │ └── typedarray@0.0.6
│ │ │ ├─┬ form-data@2.1.2
│ │ │ │ ├── asynckit@0.4.0
│ │ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ └─┬ mime-types@2.1.14
│ │ │ │   └── mime-db@1.26.0
│ │ │ ├── throwback@1.1.1
│ │ │ └─┬ tough-cookie@2.3.2
│ │ │   └── punycode@1.4.1
│ │ ├─┬ popsicle-proxy-agent@3.0.0
│ │ │ ├─┬ http-proxy-agent@1.0.0
│ │ │ │ └─┬ agent-base@2.0.1
│ │ │ │   └── semver@5.0.3
│ │ │ └── https-proxy-agent@1.0.0
│ │ ├── popsicle-retry@3.2.1
│ │ ├── popsicle-rewrite@1.0.0
│ │ ├── popsicle-status@2.0.0
│ │ ├── promise-finally@2.2.1
│ │ ├─┬ rc@1.1.7
│ │ │ ├── deep-extend@0.4.1
│ │ │ ├── ini@1.3.4
│ │ │ ├── minimist@1.2.0
│ │ │ └── strip-json-comments@2.0.1
│ │ ├─┬ sort-keys@1.1.2
│ │ │ └── is-plain-obj@1.1.0
│ │ ├── string-template@1.0.0
│ │ ├── thenify@3.2.1
│ │ ├── throat@3.0.0
│ │ ├─┬ touch@1.0.0
│ │ │ └── nopt@1.0.10
│ │ └── zip-object@0.1.0
│ └─┬ typings-global@1.0.14
│   ├── semver@5.3.0
│   └── shelljs@0.7.6
├─┬ merge-stream@1.0.1
│ └─┬ readable-stream@2.2.3
│   ├── buffer-shims@1.0.0
│   ├── core-util-is@1.0.2
│   ├── isarray@1.0.0
│   ├── process-nextick-args@1.0.7
│   ├── string_decoder@0.10.31
│   └── util-deprecate@1.0.2
├─┬ mocha@3.2.0
│ ├── browser-stdout@1.3.0
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.5
│ ├── glob@7.0.5
│ ├── growl@1.9.2
│ ├── json3@3.3.2
│ ├─┬ lodash.create@3.1.1
│ │ ├── lodash._baseassign@3.2.0
│ │ ├── lodash._basecreate@3.0.3
│ │ └── lodash._isiterateecall@3.0.9
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ supports-color@3.1.2
│   └── has-flag@1.0.0
├─┬ multipipe@1.0.2
│ └── duplexer2@0.1.4
├── parse5@2.2.3
├─┬ plylog@0.4.0
│ └─┬ winston@2.3.1
│   ├── async@1.0.0
│   ├── colors@1.0.3
│   ├── cycle@1.0.3
│   ├── eyes@0.1.8
│   ├── isstream@0.1.2
│   └── stack-trace@0.0.9
├─┬ polymer-analyzer@2.0.0-alpha.27
│ ├── @types/chai-subset@1.3.0
│ ├── @types/chalk@0.4.31
│ ├── @types/cssbeautify@0.3.1
│ ├── @types/doctrine@0.0.1
│ ├── @types/escodegen@0.0.2
│ ├── @types/estraverse@0.0.2
│ ├── @types/estree@0.0.34
│ ├── @types/node@6.0.63
│ ├── @types/split@0.3.28
│ ├── cssbeautify@0.3.1
│ ├─┬ doctrine@2.0.0
│ │ └── esutils@2.0.2
│ ├─┬ escodegen@1.8.1
│ │ ├── esprima@2.7.3
│ │ ├── estraverse@1.9.3
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ ├── levn@0.3.0
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.2
│ │ │ └── wordwrap@1.0.0
│ │ └─┬ source-map@0.2.0
│ │   └── amdefine@1.0.1
│ ├─┬ espree@3.4.0
│ │ ├── acorn@4.0.4
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├── estraverse@3.1.0
│ ├── jsonschema@1.1.1
│ ├── shady-css-parser@0.0.8
│ ├── split@1.0.0
│ └── strip-indent@2.0.0
├─┬ polymer-bundler@2.0.0-pre.7
│ ├─┬ command-line-args@3.0.5
│ │ ├── array-back@1.0.4
│ │ ├── feature-detect-es6@1.3.1
│ │ ├─┬ find-replace@1.0.3
│ │ │ └── test-value@2.1.0
│ │ └── typical@2.6.0
│ ├─┬ command-line-usage@3.0.8
│ │ ├── ansi-escape-sequences@3.0.0
│ │ └─┬ table-layout@0.3.0
│ │   └─┬ wordwrapjs@2.0.0
│ │     └── reduce-flatten@1.0.1
│ ├── es6-promise@2.3.0
│ ├─┬ nopt@3.0.6
│ │ └── abbrev@1.1.0
│ └── path-posix@1.0.0
├─┬ polymer-project-config@2.0.0
│ ├── @types/node@6.0.63
│ └── minimatch-all@1.1.0
├── run-sequence@1.2.2
├─┬ sinon@1.17.7
│ ├── formatio@1.1.1
│ ├── lolex@1.3.2
│ ├── samsam@1.1.2
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
├─┬ sw-precache@4.3.0
│ ├─┬ dom-urls@1.1.0
│ │ └── urijs@1.18.7
│ ├── es6-promise@4.0.5
│ ├── lodash.defaults@4.2.0
│ ├─┬ lodash.template@4.4.0
│ │ └── lodash.templatesettings@4.1.0
│ ├─┬ meow@3.7.0
│ │ ├─┬ camelcase-keys@2.1.0
│ │ │ └── camelcase@2.1.1
│ │ ├─┬ loud-rejection@1.6.0
│ │ │ ├─┬ currently-unhandled@0.4.1
│ │ │ │ └── array-find-index@1.0.2
│ │ │ └── signal-exit@3.0.2
│ │ ├── map-obj@1.0.1
│ │ ├── minimist@1.2.0
│ │ ├─┬ normalize-package-data@2.3.5
│ │ │ ├── hosted-git-info@2.2.0
│ │ │ ├── is-builtin-module@1.0.0
│ │ │ └─┬ validate-npm-package-license@3.0.1
│ │ │   ├─┬ spdx-correct@1.0.2
│ │ │   │ └── spdx-license-ids@1.2.2
│ │ │   └── spdx-expression-parse@1.0.4
│ │ ├─┬ redent@1.0.0
│ │ │ ├── indent-string@2.1.0
│ │ │ └─┬ strip-indent@1.0.1
│ │ │   └── get-stdin@4.0.1
│ │ └── trim-newlines@1.0.0
│ ├─┬ pretty-bytes@3.0.1
│ │ └── number-is-nan@1.0.1
│ └─┬ sw-toolbox@3.6.0
│   ├─┬ path-to-regexp@1.7.0
│   │ └── isarray@0.0.1
│   └── serviceworker-cache-polyfill@4.0.0
├─┬ temp@0.8.3
│ ├── os-tmpdir@1.0.2
│ └── rimraf@2.2.8
├─┬ tslint@4.4.2
│ ├─┬ babel-code-frame@6.22.0
│ │ └── js-tokens@3.0.1
│ ├── colors@1.1.2
│ ├── diff@3.2.0
│ ├─┬ findup-sync@0.3.0
│ │ └── glob@5.0.15
│ ├─┬ optimist@0.6.1
│ │ └── wordwrap@0.0.3
│ └─┬ update-notifier@1.0.3
│   ├─┬ boxen@0.6.0
│   │ ├── ansi-align@1.1.0
│   │ ├── cli-boxes@1.0.0
│   │ ├── filled-array@1.1.0
│   │ └── widest-line@1.0.0
│   ├── is-npm@1.0.0
│   ├─┬ latest-version@2.0.0
│   │ └─┬ package-json@2.4.0
│   │   ├─┬ got@5.7.1
│   │   │ ├─┬ create-error-class@3.0.2
│   │   │ │ └── capture-stack-trace@1.0.0
│   │   │ ├── is-redirect@1.0.0
│   │   │ ├── is-retry-allowed@1.1.0
│   │   │ ├── lowercase-keys@1.0.0
│   │   │ ├── node-status-codes@1.0.0
│   │   │ ├── read-all-stream@3.1.0
│   │   │ ├── timed-out@3.1.3
│   │   │ ├── unzip-response@1.0.2
│   │   │ └─┬ url-parse-lax@1.0.0
│   │   │   └── prepend-http@1.0.4
│   │   ├── registry-auth-token@3.1.0
│   │   └── registry-url@3.1.0
│   ├── lazy-req@1.1.0
│   ├── semver-diff@2.1.0
│   └── xdg-basedir@2.0.0
├── typescript@2.2.1
├─┬ vinyl@1.2.0
│ ├── clone@1.0.2
│ ├── clone-stats@0.0.1
│ └── replace-ext@0.0.1
├─┬ vinyl-fs@2.4.4
│ ├─┬ duplexify@3.5.0
│ │ ├─┬ end-of-stream@1.0.0
│ │ │ └── once@1.3.3
│ │ └── stream-shift@1.0.0
│ ├─┬ glob-stream@5.3.5
│ │ ├── glob@5.0.15
│ │ ├─┬ glob-parent@3.1.0
│ │ │ ├─┬ is-glob@3.1.0
│ │ │ │ └── is-extglob@2.1.1
│ │ │ └── path-dirname@1.0.2
│ │ ├─┬ micromatch@2.3.11
│ │ │ ├─┬ arr-diff@2.0.0
│ │ │ │ └── arr-flatten@1.0.1
│ │ │ ├── array-unique@0.2.1
│ │ │ ├─┬ braces@1.8.5
│ │ │ │ ├─┬ expand-range@1.8.2
│ │ │ │ │ └─┬ fill-range@2.2.3
│ │ │ │ │   ├── is-number@2.1.0
│ │ │ │ │   ├── randomatic@1.1.6
│ │ │ │ │   └── repeat-string@1.6.1
│ │ │ │ ├── preserve@0.2.0
│ │ │ │ └── repeat-element@1.1.2
│ │ │ ├─┬ expand-brackets@0.1.5
│ │ │ │ └── is-posix-bracket@0.1.1
│ │ │ ├─┬ extglob@0.3.2
│ │ │ │ └── is-extglob@1.0.0
│ │ │ ├── filename-regex@2.0.0
│ │ │ ├── is-extglob@1.0.0
│ │ │ ├── is-glob@2.0.1
│ │ │ ├─┬ kind-of@3.1.0
│ │ │ │ └── is-buffer@1.1.4
│ │ │ ├── normalize-path@2.0.1
│ │ │ ├─┬ object.omit@2.0.1
│ │ │ │ ├─┬ for-own@0.1.5
│ │ │ │ │ └── for-in@1.0.1
│ │ │ │ └── is-extendable@0.1.1
│ │ │ ├─┬ parse-glob@3.0.4
│ │ │ │ ├─┬ glob-base@0.3.0
│ │ │ │ │ ├── glob-parent@2.0.0
│ │ │ │ │ └─┬ is-glob@2.0.1
│ │ │ │ │   └── is-extglob@1.0.0
│ │ │ │ ├── is-dotfile@1.0.2
│ │ │ │ ├── is-extglob@1.0.0
│ │ │ │ └── is-glob@2.0.1
│ │ │ └─┬ regex-cache@0.4.3
│ │ │   ├── is-equal-shallow@0.1.3
│ │ │   └── is-primitive@2.0.0
│ │ ├─┬ ordered-read-streams@0.3.0
│ │ │ └── is-stream@1.1.0
│ │ ├─┬ through2@0.6.5
│ │ │ └─┬ readable-stream@1.0.34
│ │ │   └── isarray@0.0.1
│ │ ├─┬ to-absolute-glob@0.1.1
│ │ │ └── extend-shallow@2.0.1
│ │ └─┬ unique-stream@2.2.1
│ │   └─┬ json-stable-stringify@1.0.1
│ │     └── jsonify@0.0.0
│ ├─┬ gulp-sourcemaps@1.6.0
│ │ └── convert-source-map@1.4.0
│ ├── is-valid-glob@0.3.0
│ ├── lazystream@1.0.0
│ ├── lodash.isequal@4.5.0
│ ├─┬ strip-bom@2.0.0
│ │ └── is-utf8@0.2.1
│ ├─┬ strip-bom-stream@1.0.0
│ │ └── first-chunk-stream@1.0.0
│ ├── through2-filter@2.0.0
│ └── vali-date@1.0.0
└─┬ vinyl-fs-fake@1.1.0
  ├─┬ through2@0.6.5
  │ └─┬ readable-stream@1.0.34
  │   └── isarray@0.0.1
  ├─┬ vinyl@0.4.6
  │ └── clone@0.2.0
  └─┬ vinyl-fs@0.3.14
    ├─┬ glob-stream@3.1.18
    │ ├── glob@4.5.3
    │ ├── minimatch@2.0.10
    │ ├── ordered-read-streams@0.1.0
    │ └── unique-stream@1.0.0
    ├── graceful-fs@3.0.11
    └── strip-bom@1.0.0

npm ERR! Linux 3.4.0+
npm ERR! argv "/home/maxw/.nvm/versions/node/v7.6.0/bin/node" "/home/maxw/.nvm/versions/node/v7.6.0/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! path /home/maxw/tmp/polymer-build/node_modules/.staging/istanbul-e77aaa30
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at whenOldMovedAway (/home/maxw/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/install/action/finalize.js:47:5)
npm ERR!     at /home/maxw/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/utils/rename.js:13:14
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EACCES: permission denied, rename '/home/maxw/tmp/polymer-build/node_modules/.staging/istanbul-e77aaa30' -> '/home/maxw/tmp/polymer-build/node_modules/istanbul'
npm ERR!  { Error
npm ERR!     at whenOldMovedAway (/home/maxw/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/install/action/finalize.js:47:5)
npm ERR!     at /home/maxw/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/utils/rename.js:13:14
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EACCES: permission denied, rename '/home/maxw/tmp/polymer-build/node_modules/.staging/istanbul-e77aaa30' -> '/home/maxw/tmp/polymer-build/node_modules/istanbul' parent: 'polymer-build' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/maxw/tmp/polymer-build/npm-debug.log
maxw@polymer-build$
```

I'm not sure how to upload a file in the ubuntu environment, else I'd upload that npm-debug.log file. It's easy enough to reproduce though.
