### ISSUE TITLE
nodejs v6.2.0  not work

### ISSUE THREAD

**Issue by callmelanmao** [Microsoft/BashOnWindows#426]
install nodejs v.6.2.0 with nvm, when run npm it report 
```
Error: Unknown system error -25: Unknown system error -25, open '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by benhillis** [comment]
We have a number of tty changes inbound which may unblock this (-25 is ENOTTY).  Are you running a specific npm command that I can try to make sure this is resolved?

**Comment by benhillis** [comment]
I tried this locally and was able to use npm 3.8.9 (npm version included in  node 6.2.0) to install grunt.  Let me know if you have a more specific repro you'd like me to use, thanks!

```
C:\Users\KernelTest\AppData\Local\lxss>bash ~
root@BENHILL-VM7:~# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7766  100  7766    0     0  19057      0 --:--:-- --:--:-- --:--:-- 20436
=> Downloading nvm from git to '/root/.nvm'
=> Cloning into '/root/.nvm'...
remote: Counting objects: 4703, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4703 (delta 0), reused 0 (delta 0), pack-reused 4699
Receiving objects: 100% (4703/4703), 1.23 MiB | 785.00 KiB/s, done.
Resolving deltas: 100% (2793/2793), done.
Checking connectivity... done.
* (detached from v0.31.1)
  master

=> Appending source string to /root/.bashrc
=> Close and reopen your terminal to start using nvm
root@BENHILL-VM7:~# exit
exit

C:\Users\KernelTest\AppData\Local\lxss>bash ~
root@BENHILL-VM7:~# nvm install 6.2.0
Downloading https://nodejs.org/dist/v6.2.0/node-v6.2.0-linux-x64.tar.xz...
######################################################################## 100.0%
Now using node v6.2.0 (npm v3.8.9)
Creating default alias: default -> 6.2.0 (-> v6.2.0)
root@BENHILL-VM7:~# npm

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.9 /root/.nvm/versions/node/v6.2.0/lib/node_modules/npm
root@BENHILL-VM7:~# npm install grunt
/root
└─┬ grunt@1.0.1
  ├── coffee-script@1.10.0
  ├─┬ dateformat@1.0.12
  │ ├── get-stdin@4.0.1
  │ └─┬ meow@3.7.0
  │   ├─┬ camelcase-keys@2.1.0
  │   │ └── camelcase@2.1.1
  │   ├── decamelize@1.2.0
  │   ├─┬ loud-rejection@1.3.0
  │   │ ├── array-find-index@1.0.1
  │   │ └── signal-exit@2.1.2
  │   ├── map-obj@1.0.1
  │   ├── minimist@1.2.0
  │   ├─┬ normalize-package-data@2.3.5
  │   │ ├── hosted-git-info@2.1.5
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.1.0
  │   │ └─┬ validate-npm-package-license@3.0.1
  │   │   ├─┬ spdx-correct@1.0.2
  │   │   │ └── spdx-license-ids@1.2.1
  │   │   └─┬ spdx-expression-parse@1.0.2
  │   │     └── spdx-exceptions@1.0.4
  │   ├── object-assign@4.1.0
  │   ├─┬ read-pkg-up@1.0.1
  │   │ ├─┬ find-up@1.1.2
  │   │ │ ├── path-exists@2.1.0
  │   │ │ └─┬ pinkie-promise@2.0.1
  │   │ │   └── pinkie@2.0.4
  │   │ └─┬ read-pkg@1.1.0
  │   │   ├─┬ load-json-file@1.1.0
  │   │   │ ├── graceful-fs@4.1.4
  │   │   │ ├─┬ parse-json@2.2.0
  │   │   │ │ └─┬ error-ex@1.3.0
  │   │   │ │   └── is-arrayish@0.2.1
  │   │   │ ├── pify@2.3.0
  │   │   │ └─┬ strip-bom@2.0.0
  │   │   │   └── is-utf8@0.2.1
  │   │   └── path-type@1.1.0
  │   ├─┬ redent@1.0.0
  │   │ ├─┬ indent-string@2.1.0
  │   │ │ └─┬ repeating@2.0.1
  │   │ │   └─┬ is-finite@1.0.1
  │   │ │     └── number-is-nan@1.0.0
  │   │ └── strip-indent@1.0.1
  │   └── trim-newlines@1.0.0
  ├── eventemitter2@0.4.14
  ├── exit@0.1.2
  ├─┬ findup-sync@0.3.0
  │ └── glob@5.0.15
  ├─┬ glob@7.0.3
  │ ├─┬ inflight@1.0.5
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.1
  │ └── once@1.3.3
  ├─┬ grunt-cli@1.2.0
  │ └── resolve@1.1.7
  ├── grunt-known-options@1.1.0
  ├─┬ grunt-legacy-log@1.0.0
  │ ├── colors@1.1.2
  │ ├─┬ grunt-legacy-log-utils@1.0.0
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├── strip-ansi@3.0.1
  │ │ │ └── supports-color@2.0.0
  │ │ └── lodash@4.3.0
  │ ├── hooker@0.2.3
  │ ├── lodash@3.10.1
  │ └── underscore.string@3.2.3
  ├─┬ grunt-legacy-util@1.0.0
  │ ├── async@1.5.2
  │ ├── getobject@0.1.0
  │ ├── lodash@4.3.0
  │ └─┬ which@1.2.9
  │   └── isexe@1.1.2
  ├── iconv-lite@0.4.13
  ├─┬ js-yaml@3.5.5
  │ ├─┬ argparse@1.0.7
  │ │ └── sprintf-js@1.0.3
  │ └── esprima@2.7.2
  ├─┬ minimatch@3.0.0
  │ └─┬ brace-expansion@1.1.4
  │   ├── balanced-match@0.4.1
  │   └── concat-map@0.0.1
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.0.7
  ├── path-is-absolute@1.0.0
  └── rimraf@2.2.8

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
root@BENHILL-VM7:~# npm -v
3.8.9
root@BENHILL-VM7:~# node -v
v6.2.0
root@BENHILL-VM7:~#
```

**Comment by JasonDunbar** [comment]
Also eagerly awaiting a fix for this. When can we likely expect it?

**Comment by callmelanmao** [comment]
@benhillis 

under windows build 14352
```
 nvm install v6.2.0
Downloading https://nodejs.org/dist/v6.2.0/node-v6.2.0-linux-x64.tar.xz...
######################################################################## 100.0%
WARNING: checksums are currently disabled for node.js v4.0 and later
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: Unknown system error -25: Unknown system error -25, open '/home/webmaster/.nvm/versions/node/v6.2.0/lib/node_modules/npm/bin/npm-cli.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.Module._extensions..js (module.js:549:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v6.2.0` to unset it.
```

**Comment by benhillis** [comment]
There is some tty work in the build I was running above. Those changes will be in an Insider build soon.

**Comment by callmelanmao** [comment]
@benhillis 

got it, look forward the Windows 10 Anniversary Update

**Comment by russalex** [comment]
@benhillis's fix is in build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
