### ISSUE TITLE
NodeJS "Error loading resource"

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/BashOnWindows#438]
During a JS build / optimize process _and_ during a unit test (phantomjs) NodeJS is unable to load "static" resources:

During build:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Broken @import declaration of "http://fonts.googleapis.com/css?family=Lato:400" - timeout
```

During unit test:
```
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53072 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/2/2/1.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=visres.25921 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/0/0/0.png (5). Details: Operation canceled
Error loading resource http://maps.gstatic.com/mapfiles/api-3/images/mapcnt6.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53414 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.52335 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53533 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.24327 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.52968 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo?1m6&1m2&1d35.26780310620408&2d-136.78188502000773&2m2&1d50.04215305610038&2d-57.66762399798233&2u4&4sen-US&5e0&6sm%40351000000&7b0&8e0&9b0&callback=_xdc_._q0gaxr&token=94109 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.23721 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53313 (5). Details: Operation canceled
Error loading resource http://fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUaCWcynf_cDxXwCLxiixG1c.ttf (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.52331 (5). Details: Operation canceled
Error loading resource http://a.tile.openstreetmap.org/2/1/2.png (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/api/js/StaticMapService.GetMapImage?1m2&1i795&2i1474&2e1&3u4&4m2&1u291&2u66&5m5&1e0&5sen-US&6sus&10b1&12b1&token=70714 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.24060 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=true&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.54059 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=staticmap.23769,firstpixel.23769,allpixels.23769 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/gen_204?target=api&ev=api_viewport&cad=host:,v:24,r:1,mt:m,c:42.476814%2C-97.380979,sp:14.09994x27.50977,size:313x219,relsize:0.57,token:6f8rjforb6,src:apiv3,ts:p8p4e3 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/gen_204?target=api&ev=api_viewport&cad=host:,v:24,r:1,mt:m,c:42.841155%2C-97.380979,sp:4.25072x25.57617,size:291x66,relsize:0.16,token:6f8rjforb6,src:apiv3,ts:p8pero (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53986 (5). Details: Operation canceled
Error loading resource http://maps.gstatic.com/mapfiles/api-3/images/sv5.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53242 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/gen_204?target=api&ev=api_viewport&cad=host:,v:24,r:1,mt:m,c:42.831753%2C-97.380979,sp:4.76592x26.19141,size:298x74,relsize:0.18,token:6f8rjforb6,src:apiv3,ts:p8pell (5). Details: Operation canceled
Error loading resource http://fonts.gstatic.com/s/roboto/v15/zN7GBFwfMP4uA6AR0HCoLQ.ttf (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.52972 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=visres.25253 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=staticmap.22965,firstpixel.22965,allpixels.22965 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=visres.24274 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53988 (5). Details: Operation canceled
Error loading resource http://fonts.gstatic.com/s/roboto/v15/Hgo13k-tfSpn0qi1SFdUfaCWcynf_cDxXwCLxiixG1c.ttf (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=staticmap.24165,firstpixel.24165,allpixels.24165 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/1/0/0.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53135 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=staticmap.24619,firstpixel.24619,allpixels.24619 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/api/js/StaticMapService.GetMapImage?1m2&1i791&2i1470&2e1&3u4&4m2&1u298&2u74&5m5&1e0&5sen-US&6sus&10b1&12b1&token=100997 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/1/1/0.png (5). Details: Operation canceled
Error loading resource http://maps.gstatic.com/mapfiles/api-3/images/tmapctrl.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=staticmap.23947,firstpixel.23947,allpixels.23947 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.23889 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53316 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/2/1/1.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53245 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=visres.25471 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=true&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.54055 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.23618 (5). Details: Operation canceled
Error loading resource http://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOKCWcynf_cDxXwCLxiixG1c.ttf (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/2/2/2.png (5). Details: Operation canceled
Error loading resource http://c.tile.openstreetmap.org/1/1/0.png (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/1/1/1.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=visres.25077 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=true&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=visres.24692 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53140 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53075 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/1/0/1.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53418 (5). Details: Operation canceled
Error loading resource http://b.tile.openstreetmap.org/2/1/2.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53688 (5). Details: Operation canceled
Error loading resource http://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo?1m6&1m2&1d36.131117826688545&2d-136.02303181812158&2m2&1d49.30834903406907&2d-58.65993247156496&2u4&4sen-US&5e0&6sm%40351000000&7b0&8e0&9b0&callback=_xdc_._bwt4gk&token=44923 (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=313x219&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.53537 (5). Details: Operation canceled
Error loading resource http://a.tile.openstreetmap.org/2/1/1.png (5). Details: Operation canceled
Error loading resource http://a.tile.openstreetmap.org/2/2/1.png (5). Details: Operation canceled
Error loading resource http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=24.11a&action=map2&firstmap=false&hdpi=false&mob=true&staticmap=true&size=320x240&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.53685 (5). Details: Operation canceled
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, can you please provide repro steps so we can try it out locally?

**Comment by GordonSmith** [comment]
(install nodejs v6.2.0)
```
mkdir ./someDir
cd ./someDir
git clone https://github.com/hpcc-systems/Visualization.git
cd Visualization
git checkout candidate-1.14.x
npm install -g gulp
npm install -g bower
npm install
bower install
sudo apt-get install phantomjs
gulp unitTest
```

**Comment by stehufntdev** [comment]
Thanks for sharing the repro, but I'm getting a slightly different error on a recent internal build.  Is there a configuration step I'm missing or is this unexpected?

test@TEST-6:~/gh438/Visualization$ gulp unitTest
(node:696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/test/gh438/Visualization/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by GordonSmith** [comment]
@stehufntdev I suspect something in the project changed, but manually install jshint:
```
npm install jshint
```
and then continue

**Comment by stehufntdev** [comment]
Thanks, that resolved the failure above.  Afterwards, I'm seeing different behavior on a recent internal build.  Is any of this unexpected:

test@TEST-6:~/gh438/Visualization$ gulp unitTest
(node:717) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[06:25:46] Using gulpfile ~/gh438/Visualization/gulpfile.js
[06:25:46] Starting 'unitTest'...


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․Error loading resource file://gg.google.com/csi?s=uds&v=2&action=al_visualization&it=jl.304 (302). Details: Request for opening non-local file file://gg.google.com/csi?s=uds&v=2&action=al_visualization&it=jl.304
․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․Unknown Property:  charttype
Unknown Property:  charttype
․Unknown Property:  charttype
Unknown Property:  charttype
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․

  741 passing (2m)
  18 pending

[06:27:42] Finished 'unitTest' after 1.93 min
test@TEST-6:~/gh438/Visualization$

**Comment by GordonSmith** [comment]
That looks better - the following two look suspect though:
```
Error loading resource file://gg.google.com/csi?s=uds&v=2&action=al_visualization&it=jl.304 (302). Details: Request for opening non-local file file://gg.google.com/csi?s=uds&v=2&action=al_visualization&it=jl.304
```

Can you now try ```npm test``` which was also failing (compared to git bash on windows).

**Comment by GordonSmith** [comment]
FYI - This issue is now resolved in 14361.  I have been unable to complete an end to end build / test via ```npm test``` due to what appears to be a memory leak / infinite loop in phantomjs.  New issue is here:  https://github.com/Microsoft/BashOnWindows/issues/489
