### ISSUE TITLE
Enabling ufw results in error

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#439]
Hi when I do 

sudo ufw enable

I get

WARN: / is group writable!
Traceback (most recent call last):
  File "/usr/sbin/ufw", line 117, in <module>
    res = ui.do_action(pr.action, "", "", pr.force)
  File "/usr/lib/python3/dist-packages/ufw/frontend.py", line 636, in do_action
    res = self.set_enabled(True)
  File "/usr/lib/python3/dist-packages/ufw/frontend.py", line 187, in set_enabled
    "ENABLED", config_str)
  File "/usr/lib/python3/dist-packages/ufw/backend.py", line 324, in set_default
    ufw.util.close_files(fns)
  File "/usr/lib/python3/dist-packages/ufw/util.py", line 269, in close_files
    shutil.copystat(fns['origname'], fns['tmpname'])
  File "/usr/lib/python3.4/shutil.py", line 213, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib/python3.4/shutil.py", line 145, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 38] Function not implemented: '/etc/ufw/ufw.conf'

error

**Comment by benhillis** [comment]
We have a change in-progress to enable the listxattr system call.

**Comment by paladox** [comment]
Oh thanks.

**Comment by therealkenc** [comment]
Heads up that listxattr wasn't listed in the new system calls in the 14361 [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) if it got added.

**Comment by benhillis** [comment]
14366 has support for listxattr

**Comment by benhillis** [comment]
This is fixed in build 14388+.  Please reopen if you continue to see issues.
