### ISSUE TITLE
nvm is not compatible with the npm config "prefix" option: currently set to ""

### ISSUE THREAD

**Issue by x0rm3r** [Microsoft/BashOnWindows#476]
```bash
x0rm3r@X0RM3R:~$ nvm install 4.4.5
Downloading https://nodejs.org/dist/v4.4.5/node-v4.4.5-linux-x64.tar.xz...
######################################################################## 100.0%
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: Unknown system error -25: Unknown system error -25, open '/home/x0rm3r/.nvm/versions/node/v4.4.5/lib/node_modules/npm/bin/npm-cli.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.5` to unset it.
```

**Comment by callodacity** [comment]
+1, I get the same, whether it's in `bash` or `zsh`. Can't install or use `node`.

    ➜  ~ node
    zsh: command not found: node
    ➜  ~ nvm use 6
    fs.js:634
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^
    
    Error: Unknown system error -25: Unknown system error -25, open     '/home/callodacity/.nvm/versions/node/v6.2.1/lib/node_modules/npm/bin/npm-cli.js'
        at Error (native)
        at Object.fs.openSync (fs.js:634:18)
        at Object.fs.readFileSync (fs.js:502:33)
        at Object.Module._extensions..js (module.js:549:20)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Function.Module.runMain (module.js:575:10)
        at startup (node.js:160:18)
        at node.js:456:3
    nvm is not compatible with the npm config "prefix" option: currently set to ""
    Run `nvm use --delete-prefix v6.2.1` to unset it.
    ➜  ~ node
    zsh: command not found: node

**Comment by russalex** [comment]
Confirmed the error on 14352.  The good news is that there is a fix inbound.  Trying this on an internal build:

> russ@RUSSALEX-BOOK:~$ nvm install 4.4.5
> Downloading https://nodejs.org/dist/v4.4.5/node-v4.4.5-linux-x64.tar.xz...
> ######################################################################## 100.0%
> Now using node v4.4.5 (npm v2.15.5)

**Comment by russalex** [comment]
Fixed in build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
