### ISSUE TITLE
babel-watch seems to fail

### ISSUE THREAD

**Issue by czbaker** [Microsoft/BashOnWindows#556]
So, I'm working on a NodeJS project, and I was going to see if it'd work in BashOnWindows, but when I go to run the `babel-watch` task (with webpack), I get the following:

```
misutowolf@DESKTOP-6568VBL:~/projects/smail-hub$ npm run dev

> node-boilerplate@1.0.0 dev /home/misutowolf/projects/smail-hub
> babel-watch -w server server/index.js

Watcher failure { Error: watch server EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/misutowolf/projects/smail-hub/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:117:15)
  code: 'EPERM',
  errno: 'EPERM',
  syscall: 'watch server',
  filename: 'server' }

npm ERR! Linux 3.4.0+
npm ERR! argv "/home/misutowolf/.nvm/versions/node/v6.2.2/bin/node" "/home/misutowolf/.nvm/versions/node/v6.2.2/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! node-boilerplate@1.0.0 dev: `babel-watch -w server server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-boilerplate@1.0.0 dev script 'babel-watch -w server server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-watch -w server server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/misutowolf/projects/smail-hub/npm-debug.log
```

Not sure if this is related to it not being POSIX-compatible (I think I read that in another issue), or what...but I'd love to get some help with this issue for sure.  I'm using the newest build that I am aware of (14367) inside a Virtualbox VM...I didn't want to use this as my normal desktop OS without being able to definitely write Node stuff with Babel/Webpack in the environment.

I suppose an alternative in the future could be writing code in Windows and temporarily using a Linux VM (or something like Vagrant) to execute the code, as you can't use `babel-watch` in Windows at all.

Thanks!

**Comment by therealkenc** [comment]
Anything using FSWatcher hits #216 and friends. `ioctl(..., FIOCLEX)` returns `EPERM`.

**Comment by czbaker** [comment]
Ah, okay.  I probably should have researched issues first before posting this.  Thanks for the link though, I'll keep an eye on the issue, won't be able to use BashForWindows for my development needs until the issue is fixed, it would seem.

**Comment by benhillis** [comment]
@czbaker No problem at all.  I'm going to go ahead and close this out as a duplicate.  File system watches are on our backlog but unfortunately won't make the Windows 10 Anniversary Update.
