### ISSUE TITLE
node-sass fails to install, due to os.networkInterfaces() EINVAL

### ISSUE THREAD

**Issue by patricksrobertson** [Microsoft/BashOnWindows#567]
Similar to #468, I'm unable to run `npm install` on my projects using the library `node-sass`.

Here's the relevant output:

```
/home/patricksroberts/src/IoraHealth/node_modules/node-sass/node_modules/npmconf/config-defs.js:332
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: EINVAL, invalid argument
    at Error (native)
    at getLocalAddresses (/home/patricksroberts/src/IoraHealth/node_modules/node-sass/node_modules/npmconf/config-defs.js:332:18)
    at Object.<anonymous> (/home/patricksroberts/src/IoraHealth/node_modules/node-sass/node_modules/npmconf/config-defs.js:281:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/patricksroberts/src/IoraHealth/node_modules/node-sass/node_modules/npmconf/npmconf.js:4:18)
```

seems to be the last failing part to my build!

**Comment by sunilmut** [comment]
Thanks for reporting the issue. We are working to enhance the networking/socket level support post Anniversary update release. Stay tuned!

**Comment by sunilmut** [comment]
Also, would you mind closing this out as a dupe of #468 ?

**Comment by patricksrobertson** [comment]
sure.

**Comment by Shokodemon** [comment]
any hope for fixing this soon ?

**Comment by aseering** [comment]
@Shokodemon -- this ticket was closed as a duplicate.  Did you intend to comment on #468 ?
