### ISSUE TITLE
Ember server hangs

### ISSUE THREAD

**Issue by malisbad** [Microsoft/BashOnWindows#587]
I was just starting the testing bit on the ember-cli tutorial, then I got this error. I also have issues with running the server without tests.

Edit: @therealkenc thanks for pointing me to a related issue. I'll close this one out.

`Error: watch /mnt/d/coding_workspace/derp-derp/app EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/d/coding_workspace/derp-derp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)`

**Comment by therealkenc** [comment]
#216 NodeWatcher
